name: Example Usage of Build & Push Container

on:
  push:

jobs:
  build-and-push:
    uses: spizzadev/workflows/.github/workflows/build-and-push-container.yml@main
    permissions:
      contents: read
      packages: write
    with:
      image-name: ${{ github.repository }}
      image-authors: ${{ github.actor }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  sign:
    needs: build-and-push
    uses: spizzadev/workflows/.github/workflows/sign-container.yml@main
    permissions:
      id-token: write
      packages: write
    with:
      image: ghcr.io/${{ github.repository }}
      digest: ${{ needs.build-and-push.outputs.digest }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
