name: Example Usage of Build & Deploy Container

# This example shows how to use the build-and-deploy-container.yml reusable workflow

on:
  # Builds on every push to main
  push:
    branches:
      - main
  
  # Manual trigger with option to force deployment
  workflow_dispatch:
    inputs:
      force-deploy:
        description: 'Force deployment even on untagged commits'
        required: false
        type: boolean
        default: false

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy-container.yml
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}
      force-deploy: ${{ github.event.inputs.force-deploy || false }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
