name: Sign Container

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: Full image reference without tag, e.g. ghcr.io/my-org/my-app
      digest:
        required: true
        type: string
        description: Image digest (sha256:...)
      registry:
        type: string
        default: ghcr.io
        description: Container registry URL
    secrets:
      username:
        required: true
        description: Registry username
      password:
        required: true
        description: Registry password or token

jobs:
  sign:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write

    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Sign the published Docker image
        run: cosign sign --yes ${{ inputs.image }}@${{ inputs.digest }}
